language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

node_js:
  - "10.2.1"

jobs:
  include:
  - name: python 3.5.4
    env: PYENV_VERSION=3.5.4
  - name: python 3.6.3
    env: PYENV_VERSION=3.6.3
  - name: python 2.7.14
    env: PYENV_VERSION=2.7.14

before_install: 
  - npm install -g npm
  - if [ -n "$PYENV_VERSION" ]; then pyenv install "$PYENV_VERSION"; fi
  - echo "python is $(command -v python), version $(python --version)" 
  - echo "python2 is $(command -v python2), version $(python2 --version)"
  - echo "python3 is $(command -v python3), version $(python3 --version)"

install: npm install

script: ./bin/npm test

git:
  depth: 10

addons:
  apt:
    packages:
      - libsecret-1-dev
      - g++-4.8
    sources:
      - ubuntu-toolchain-r-test

env:
  - CXX=g++-4.8
