language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

node_js:
  - "10.2.1"

jobs:
  include:
  - name: python is 3.5
    env: PYENV_VERSION=3.5
  - name: python is 3.8
    env: PYENV_VERSION=3.8
  - name: python is 2.7
    env: PYENV_VERSION=2.7

before_install: 
  - npm install -g npm
  - echo "python is $(command -v python), version $(python --version)" 
  - echo "python2 is $(command -v python2), version $(python2 --version)"
  - echo "python3 is $(command -v python3), version $(python3 --version)"

install: npm install

script: ./bin/npm test

git:
  depth: 10

addons:
  apt:
    packages:
      - libsecret-1-dev
      - g++-4.8
    sources:
      - ubuntu-toolchain-r-test

env:
  - CXX=g++-4.8
